global:
  scrape_interval: 5s
  external_labels:
    client: cli1
    platform: dc1

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9091','127.0.0.1:9092']