version: "3"

services:

  crawler-dc1:
    image: quay.io/prometheus/prometheus:v2.26.0
    volumes:
      - "./prom-dc1-config.yml:/etc/prometheus/prometheus.yml"
      - "./data/prom-dc1:/prometheus"
    user: root
    ports:
      - "${PROM_DC1_PORT}:${PROM_DC1_PORT}"
    command: ["--config.file=/etc/prometheus/prometheus.yml", 
    "--storage.tsdb.path=/prometheus",
    "--storage.tsdb.retention.time=1000d", 
    "--storage.tsdb.max-block-duration=2h", 
    "--storage.tsdb.min-block-duration=2h", 
    "--web.listen-address=:$PROM_DC1_PORT", 
    "--web.external-url=${PROM_DC1_EXT_ADDRESS}:$PROM_DC1_PORT", 
    "--web.enable-lifecycle",
    "--no-scrape.adjust-timestamps", 
    "--web.enable-admin-api"]

  crawler-dc2:
    image: quay.io/prometheus/prometheus:v2.26.0
    volumes:
      - "./prom-dc2-config.yml:/etc/prometheus/prometheus.yml"
      - "./data/prom-dc2:/prometheus"
    user: root
    ports:
      - "${PROM_DC2_PORT}:${PROM_DC2_PORT}"
    command: ["--config.file=/etc/prometheus/prometheus.yml", 
    "--storage.tsdb.path=/prometheus",
    "--storage.tsdb.retention.time=1000d", 
    "--storage.tsdb.max-block-duration=2h", 
    "--storage.tsdb.min-block-duration=2h", 
    "--web.listen-address=:$PROM_DC2_PORT", 
    "--web.external-url=${PROM_DC2_EXT_ADDRESS}:$PROM_DC2_PORT", 
    "--web.enable-lifecycle", 
    "--no-scrape.adjust-timestamps", 
    "--web.enable-admin-api"]


  grafana:
    image: grafana/grafana:7.2.1
    volumes:
      - "./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
      - "./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml"
      - "./grafana/dashboards/:/etc/grafana/dashboards/"
    ports:
      - "3000:3000"