version: "3"

services:

  crawler-dc1:
    image: quay.io/prometheus/prometheus:v2.26.0
    volumes:
      - "./prom-dc1-config.yml:/etc/prometheus/prometheus.yml"
      - "./data/prom-dc1:/prometheus"
    user: root
    ports:
      - "${PROM_DC1_PORT}:${PROM_DC1_PORT}"
    command: ["--config.file=/etc/prometheus/prometheus.yml", 
    "--storage.tsdb.path=/prometheus",
    "--storage.tsdb.retention.time=1000d", 
    "--storage.tsdb.max-block-duration=2h", 
    "--storage.tsdb.min-block-duration=2h", 
    "--web.listen-address=:$PROM_DC1_PORT", 
    "--web.external-url=${PROM_DC1_EXT_ADDRESS}:$PROM_DC1_PORT", 
    "--web.enable-lifecycle", 
    "--web.enable-admin-api"]

  crawler-dc2:
    image: quay.io/prometheus/prometheus:v2.26.0
    volumes:
      - "./prom-dc2-config.yml:/etc/prometheus/prometheus.yml"
      - "./data/prom-dc2:/prometheus"
    user: root
    ports:
      - "${PROM_DC2_PORT}:${PROM_DC2_PORT}"
    command: ["--config.file=/etc/prometheus/prometheus.yml", 
    "--storage.tsdb.path=/prometheus",
    "--storage.tsdb.retention.time=1000d", 
    "--storage.tsdb.max-block-duration=2h", 
    "--storage.tsdb.min-block-duration=2h", 
    "--web.listen-address=:$PROM_DC2_PORT", 
    "--web.external-url=${PROM_DC2_EXT_ADDRESS}:$PROM_DC2_PORT", 
    "--web.enable-lifecycle", 
    "--web.enable-admin-api"]

  sidecar-dc1:
    image: quay.io/thanos/thanos:v0.16.0
    volumes:
      - "./prom-dc1-config.yml:/etc/prometheus/prometheus.yml"
    user: root
    command: "sidecar --http-address 0.0.0.0:19091 \
    --grpc-address 0.0.0.0:19191 \
    --reloader.config-file /etc/prometheus/prometheus.yml \
    --prometheus.url http://crawler-dc1:${PROM_DC1_PORT}"

  sidecar-dc2:
    image: quay.io/thanos/thanos:v0.16.0
    volumes:
      - "./prom-dc2-config.yml:/etc/prometheus/prometheus.yml"
    user: root
    command: "sidecar --http-address 0.0.0.0:19092 \
    --grpc-address 0.0.0.0:19192 \
    --reloader.config-file /etc/prometheus/prometheus.yml \
    --prometheus.url http://crawler-dc2:${PROM_DC2_PORT}"

  global-query:
    image: quay.io/thanos/thanos:v0.16.0
    volumes:
      - "./prom-dc2-config.yml:/etc/prometheus/prometheus.yml"
    user: root
    ports:
      - "9090:9090"
    command: "query \
    --http-address 0.0.0.0:9090 \
    --grpc-address 0.0.0.0:19190 \
    --query.replica-label replica \
    --log.level=debug
    --store sidecar-dc1:19191 \
    --store sidecar-dc2:19192"

  grafana:
    image: grafana/grafana:7.2.1
    ports:
      - "3100:3000"